/*
* The version of the ZaloPay OpenAPI document: v1.0.0
* Contact: developer@zalopay.vn
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit this class manually.
*/

export class AgreementBalanceResponseDataInner {
  /**
  * Payment channel.
  */
  "channel"?: number;

  /**
  * If the user can pay on this channel.
  */
  "payable"?: boolean;

  /**
  * Bank code of the channel.
  */
  "bank_code"?: string;


  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    {
      "name": "channel",
      "baseName": "channel",
      "type": "number"
    },
    {
      "name": "payable",
      "baseName": "payable",
      "type": "boolean"
    },
    {
      "name": "bank_code",
      "baseName": "bank_code",
      "type": "string"
    }  ];

  static getAttributeTypeMap() {
    return AgreementBalanceResponseDataInner.attributeTypeMap;
  }
}

