/*
* The version of the ZaloPay OpenAPI document: v1.0.0
* Contact: developer@zalopay.vn
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit this class manually.
*/

export class AgreementPayRequest {
  /**
  * The unique ID of the application will be provided after the merchant registered successfully with ZaloPay.
  */
  "app_id"?: number;

  /**
  * user\'s identifier on the merchant system, it can be a merchant user\'s id, phone number, email...
  */
  "identifier": string;

  /**
  * The token is generated by API create_order.
  */
  "zp_trans_token": string;

  /**
  * The public token of the payer.
  */
  "pay_token": string;

  /**
  * Current timestamp in milliseconds.
  */
  "req_date": number;

  /**
  * It is signature of request. It\'s calculated by following input: hmacinput = app_id + `|` + identifier + `|` + zp_trans_token + `|` + pay_token + `|` + req_date; and use sha256 with app\'s hmac key as sign key.
  */
  "mac"?: string;


  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{ name: string, baseName: string, type: string }> = [
    {
      "name": "app_id",
      "baseName": "app_id",
      "type": "number"
    },
    {
      "name": "identifier",
      "baseName": "identifier",
      "type": "string"
    },
    {
      "name": "zp_trans_token",
      "baseName": "zp_trans_token",
      "type": "string"
    },
    {
      "name": "pay_token",
      "baseName": "pay_token",
      "type": "string"
    },
    {
      "name": "req_date",
      "baseName": "req_date",
      "type": "number"
    },
    {
      "name": "mac",
      "baseName": "mac",
      "type": "string"
    }];

  static getAttributeTypeMap() {
    return AgreementPayRequest.attributeTypeMap;
  }
}

