/*
* The version of the ZaloPay OpenAPI document: v1.0.0
* Contact: developer@zalopay.vn
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit this class manually.
*/

export class DisbursementQueryMerchantBalanceResponseData {
  /**
  * Partner’s account balance
  */
  "balance"?: number;


  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    {
      "name": "balance",
      "baseName": "balance",
      "type": "number"
    }  ];

  static getAttributeTypeMap() {
    return DisbursementQueryMerchantBalanceResponseData.attributeTypeMap;
  }
}

