/*
* The version of the ZaloPay OpenAPI document: v1.0.0
* Contact: developer@zalopay.vn
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit this class manually.
*/
import { GatewayGetListBanksResponseBanks } from "./gatewayGetListBanksResponseBanks";

export class GatewayGetListBanksResponse {
  /**
  * 1 - SUCCESS  2 - FAIL
  */
  "returncode"?: number;

  /**
  * Return code description
  */
  "returnmessage"?: string;

  "banks"?: GatewayGetListBanksResponseBanks;


  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    {
      "name": "returncode",
      "baseName": "returncode",
      "type": "number"
    },
    {
      "name": "returnmessage",
      "baseName": "returnmessage",
      "type": "string"
    },
    {
      "name": "banks",
      "baseName": "banks",
      "type": "GatewayGetListBanksResponseBanks"
    }  ];

  static getAttributeTypeMap() {
    return GatewayGetListBanksResponse.attributeTypeMap;
  }
}

