/*
* The version of the ZaloPay OpenAPI document: v1.0.0
* Contact: developer@zalopay.vn
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit this class manually.
*/
import { GatewayBankItem } from "./gatewayBankItem";

/**
* List of supported banks  Data type:  Map(pmcid, Array(bankdto))  Note about pcmid:    36 - Visa/Master/JCB    37 - Bank account    38 - ZaloPay    39 - ATM      41 - VISA/Master Debit
*/
export class GatewayGetListBanksResponseBanks {
  "_36"?: Array<GatewayBankItem>;

  "_37"?: Array<GatewayBankItem>;

  "_38"?: Array<GatewayBankItem>;

  "_39"?: Array<GatewayBankItem>;

  "_41"?: Array<GatewayBankItem>;


  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    {
      "name": "_36",
      "baseName": "36",
      "type": "Array<GatewayBankItem>"
    },
    {
      "name": "_37",
      "baseName": "37",
      "type": "Array<GatewayBankItem>"
    },
    {
      "name": "_38",
      "baseName": "38",
      "type": "Array<GatewayBankItem>"
    },
    {
      "name": "_39",
      "baseName": "39",
      "type": "Array<GatewayBankItem>"
    },
    {
      "name": "_41",
      "baseName": "41",
      "type": "Array<GatewayBankItem>"
    }  ];

  static getAttributeTypeMap() {
    return GatewayGetListBanksResponseBanks.attributeTypeMap;
  }
}

