/*
* The version of the ZaloPay OpenAPI document: v1.0.0
* Contact: developer@zalopay.vn
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit this class manually.
*/

export class RefundCreateRequest {
  /**
  * The unique ID of the application will be provided after the merchant registered successfully with ZaloPay.
  */
  "app_id"?: number;

  /**
  * Refund ID will be generated by the application. Format: yymmdd_appid_xxxxxxxxxx.
  */
  "m_refund_id": string;

  /**
  * ZaloPay transaction ID for refunding.
  */
  "zp_trans_id": string;

  /**
  * Amount of money for refunding.
  */
  "amount": number;

  /**
  * The timestamp that refund order was created at in ms
  */
  "timestamp": number;

  /**
  * Reason for refunding.
  */
  "description": string;

  /**
  * It is signature of order. It\'s calculated by following input: hmacinput = appid + `|` + zptransid + `|` + amount + `|` + description + `|` + timestamp and use sha256 with app\'s hmac key as sign key
  */
  "mac"?: string;


  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{ name: string, baseName: string, type: string }> = [
    {
      "name": "app_id",
      "baseName": "app_id",
      "type": "number"
    },
    {
      "name": "m_refund_id",
      "baseName": "m_refund_id",
      "type": "string"
    },
    {
      "name": "zp_trans_id",
      "baseName": "zp_trans_id",
      "type": "string"
    },
    {
      "name": "amount",
      "baseName": "amount",
      "type": "number"
    },
    {
      "name": "timestamp",
      "baseName": "timestamp",
      "type": "number"
    },
    {
      "name": "description",
      "baseName": "description",
      "type": "string"
    },
    {
      "name": "mac",
      "baseName": "mac",
      "type": "string"
    }];

  static getAttributeTypeMap() {
    return RefundCreateRequest.attributeTypeMap;
  }
}

