/*
* The version of the ZaloPay OpenAPI document: v1.0.0
* Contact: developer@zalopay.vn
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit this class manually.
*/

export class RefundCreateResponse {
  "return_code"?: number;

  "return_message"?: string;

  "sub_return_code"?: number;

  "sub_return_message"?: string;

  "refund_id"?: number;


  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    {
      "name": "return_code",
      "baseName": "return_code",
      "type": "number"
    },
    {
      "name": "return_message",
      "baseName": "return_message",
      "type": "string"
    },
    {
      "name": "sub_return_code",
      "baseName": "sub_return_code",
      "type": "number"
    },
    {
      "name": "sub_return_message",
      "baseName": "sub_return_message",
      "type": "string"
    },
    {
      "name": "refund_id",
      "baseName": "refund_id",
      "type": "number"
    }  ];

  static getAttributeTypeMap() {
    return RefundCreateResponse.attributeTypeMap;
  }
}

