/*
* The version of the ZaloPay OpenAPI document: v1.0.0
* Contact: developer@zalopay.vn
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit this class manually.
*/

/**
* Requests timestamp in ms
*/
export class ZodCreateInvoiceRequestOrderInfoInner {
  /**
  * Order\'s tracking number
  */
  "trackingNumber"?: string;

  /**
  * Order\'s description
  */
  "description"?: string;

  /**
  * Order\'s amount
  */
  "amount"?: number;


  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    {
      "name": "trackingNumber",
      "baseName": "trackingNumber",
      "type": "string"
    },
    {
      "name": "description",
      "baseName": "description",
      "type": "string"
    },
    {
      "name": "amount",
      "baseName": "amount",
      "type": "number"
    }  ];

  static getAttributeTypeMap() {
    return ZodCreateInvoiceRequestOrderInfoInner.attributeTypeMap;
  }
}

