/*
* The version of the ZaloPay OpenAPI document: v1.0.0
* Contact: developer@zalopay.vn
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit this class manually.
*/
import { ZodCreateInvoiceRequestOrderInfoInner } from "./zodCreateInvoiceRequestOrderInfoInner";
import { ZodCreateInvoiceRequestReceiver } from "./zodCreateInvoiceRequestReceiver";

export class ZodCreateInvoiceRequest {
  /**
  * AppID provided by ZaloPay
  */
  "appId"?: string;

  /**
  * Merchant\'s reference ID of the order
  */
  "mcRefId": string;

  /**
  * The merchant\'s hub ID
  */
  "hubId"?: string;

  /**
  * The driver ID
  */
  "driverId"?: string;

  /**
  * Requests timestamp in ms
  */
  "amount": number;

  "receiver": ZodCreateInvoiceRequestReceiver;

  "orderInfo": Array<ZodCreateInvoiceRequestOrderInfoInner>;

  /**
  * JSOn string used for external info: merchandiseSubtotal, shippingSubtotal  Ex: \"{\\\"merchandiseSubtotal\\\":100000, \\\"shippingSubtotal\\\":10000}\"
  */
  "mcExtInfo": string;

  /**
  * It is signature of request. It’s calculated by following input: hmacInput = (appId + “|” + mcRefId + “|” + amount + “|” + mcExtInfo) and use sha256 with app’s hmac key
  */
  "mac"?: string;


  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    {
      "name": "appId",
      "baseName": "appId",
      "type": "string"
    },
    {
      "name": "mcRefId",
      "baseName": "mcRefId",
      "type": "string"
    },
    {
      "name": "hubId",
      "baseName": "hubId",
      "type": "string"
    },
    {
      "name": "driverId",
      "baseName": "driverId",
      "type": "string"
    },
    {
      "name": "amount",
      "baseName": "amount",
      "type": "number"
    },
    {
      "name": "receiver",
      "baseName": "receiver",
      "type": "ZodCreateInvoiceRequestReceiver"
    },
    {
      "name": "orderInfo",
      "baseName": "orderInfo",
      "type": "Array<ZodCreateInvoiceRequestOrderInfoInner>"
    },
    {
      "name": "mcExtInfo",
      "baseName": "mcExtInfo",
      "type": "string"
    },
    {
      "name": "mac",
      "baseName": "mac",
      "type": "string"
    }  ];

  static getAttributeTypeMap() {
    return ZodCreateInvoiceRequest.attributeTypeMap;
  }
}

